### ISSUE TITLE
ePBS Perfnet

### ISSUE THREAD

**Issue by kamilchodola** [NethermindEth/eth-perf-research#43]

**Comment by kamilchodola** [comment]
@cbermudez97 

We need 4 Kurtosis setups (ideally on 4 identical machines).
1 - 12 seconds slot (current Ethereum spec)
2 - 6 seconds (current Ethereum spec)
3- 12 seconds (ePBS)
4 - 6 seconds (ePBS)

All of these should have similar Spamoor setup to emulate similar load.
All of them should ideally report to single Grafana instance with 4 separate directories.

Once all set - contact Potuz and let him analyze the data.

Only nethermind-prysm client pairs here can be used.

Prysm branch "epbs"

**Comment by kamilchodola** [comment]
Initial test executed, results published.
Sample Kurtosis config for ePBS 12 sec (most important for now):

```
# 1) One participant running Nethermind (master) + Prysm (latest) with separate VC
participants:
  - el_type: nethermind
    el_image: nethermindeth/nethermind:master

    cl_type: prysm
    # Use your custom Prysm Beacon Chain image
    cl_image: ethpandaops/prysm-beacon-chain:epbs

    use_separate_vc: true
    vc_type: prysm
    # Use your custom Prysm Validator image
    vc_image: ethpandaops/prysm-validator:epbs

    count: 2
    snooper_enabled: true

# … rest of your config unchanged …

# 2) 6-second slots and 1 Giga-gas block limit
network_params:
  seconds_per_slot: 12
  gas_limit: 1000000000
  genesis_gaslimit: 1000000000
  eip7732_fork_epoch: 1

# 3) Enable Prometheus, Grafana, Spamoor & Dora
additional_services:
  - prometheus
  - grafana
  - spamoor
  - dora

# 4) Spamoor scenarios
spamoor_params:
  spammers:
    # a) gasburner
    - scenario: gasburnertx
      config:
        throughput: 200
        max_pending: 200
        max_wallets: 100

    # b) calltx
    - scenario: calltx
      config:
        # wallet refill settings
        seed: calltx-281966
        refill_amount: 5000000000000000000    # 5 ETH
        refill_balance: 1000000000000000000   # refill when < 1 ETH
        refill_interval: 600                  # every 10 minutes

        # calltx parameters
        total_count: 0
        throughput: 20
        max_pending: 100
        max_wallets: 20
        rebroadcast: 24
        base_fee: 0
        tip_fee: 0
        deploy_gas_limit: 20000000
        gas_limit: 95000000
        amount: 0
        random_amount: false
        random_target: false

        # contract info (inline code)
        contract_code: "7d617f155f527f81d9d4d7eb0e3cdc75739f7098479097d579573f23e70b075f527fcbd40a5d97bbc1606020527f00527f18da69b1d2cb7b89fdb3bba2524bf135456020527f3ce828faea190d8f4d48d5726040527fcbe3fe6020527f2034b5942fbdd612f26040527f553a9fd9fa5eb4c3e5ce6a34ed100f626060527fde0e380f4e67f86040527f016060527f6027893e1f5082bdc48651667776e2b1e32a85ed6080527fd33ff430eef15e8e6080527f68b3d46060525b604060006080600060066096fa5060905660a05260a2601ef360a05260be60025ff0"
        contract_file: ""
        contract_address: ""
        contract_args: ""
        contract_addr_path: ".1"
        call_data: ""
        call_abi: ""
        call_abi_file: ""
        call_fn_name: ""
        call_fn_sig: ""
        call_args: ""
        client_group: ""

# 5) Dora defaults
dora_params:
  image: "ethpandaops/dora:latest"
  env: {}

# 6) Expose Grafana (and other services) externally
port_publisher:
  additional_services:
    enabled: true
    public_port_start: 36000

# 7) Enable snooping globally (optional, since enabled per‐participant above)
snooper_enabled: true
```
